# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 640)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("/* **********************\n"
"                Global \n"
"*************************/\n"
"#mainWidget {\n"
"    background-color: #393836;\n"
"}\n"
"\n"
"#ProductPage, #OrderPage, #statisticsPage, #CustomerPage {\n"
"    background: transparent;\n"
"}\n"
"/* **********************\n"
"                Global \n"
"*************************/\n"
"\n"
"QMainWindow::separator {  /* for the dockWidget line */\n"
"    width: 2px;\n"
"    background-color: #4c4c4c;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: brown;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QStatusBar QLabel {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border: 1px solid red;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/* **********************\n"
"                QPushButton \n"
"*************************/\n"
"QPushButton {    \n"
"    font: 12pt \"Noto Serif Thai\";\n"
"    background: #4b4b4b;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"    padding: 7px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: #555555;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 3px;\n"
"}\n"
"QPushButton:!enabled\n"
"{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* **********************\n"
"                QLabel \n"
"*************************/\n"
"QLabel {\n"
"    font: 12pt \"Noto Serif Thai\";\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#labelErrorProductPage, \n"
"#labelErrorOrderPage,\n"
"#labelErrorCustomerPage\n"
"{\n"
"    color: rgb(192, 28, 40);\n"
"}\n"
"\n"
"/* **********************\n"
"                LineEdits \n"
"*************************/\n"
"QLineEdit, \n"
"QDateEdit, \n"
"QSpinBox, \n"
"QDoubleSpinBox {\n"
"    font: 12pt \"Noto Serif Thai\";\n"
"    color: #ffffff;\n"
"    background: #393836;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QLineEdit:hover, \n"
"QDateEdit:hover,\n"
"QSpinBox:hover, \n"
"QDoubleSpinBox:hover {\n"
"    border: 2px solid     #4c4c4c;\n"
"}\n"
"QLineEdit:focus,\n"
"QSpinBox:focus,\n"
"QDateEdit:focus, \n"
"QDoubleSpinBox:focus\n"
"{\n"
"    background-color: rgba(51, 50, 50, 172);\n"
"    border: 2px solid #4c4c4c;\n"
"}\n"
"\n"
"/* ****************\n"
"     MENU FRAME \n"
"**************************/\n"
"\n"
"#menuFrame {\n"
"    background-color: #272727;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #202020;\n"
"    padding: 0px 5px;\n"
"}\n"
"\n"
"#menuFrame QPushButton {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    text-align: right;\n"
"}\n"
"\n"
"#menuFrame QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"#menuFrame QPushButton:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#menuFrame QPushButton:checked {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"#menuFrame #buttonUsername {\n"
"    font-size: 12pt;\n"
"    background-color: rgba(34, 112, 147, 236);\n"
"    border-radius: 25px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/****************\n"
"**    Os Info Page\n"
"******************************/\n"
"#cardInfoPage, #stWidgetInfoPage, #stWidgetOsInfoPage {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#stWidgetInfoPage, #stWidgetOsInfoPage {\n"
"    background-color: #272727;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #383838;\n"
"}\n"
"\n"
"#stWidgetInfoPage QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"    font-size: 10pt;\n"
"    padding: 10px 15px;\n"
"}\n"
"\n"
"#stWidgetInfoPage QPushButton:hover {\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"#stWidgetInfoPage QPushButton:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#labelName, #labelVersion, \n"
"#labelPlatform, #labelArch,\n"
" #labelCpu, #labelRam {    \n"
"    font: 11pt \"Ubuntu\";\n"
"    color: #8b8b8b;\n"
"}\n"
"\n"
"#labelNameValue, #labelVersionValue, \n"
"#labelPlatformValue, #labelArchValue,\n"
"#labelCpuValue, #labelRamValue \n"
"{        \n"
"    font: 16pt \"Ubuntu\";\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/*****************************\n"
"**    SEARCH FRAME\n"
"******************************/\n"
"#searchFrame, \n"
"#searchFrame_2, \n"
"#searchFrame_3 \n"
"{\n"
"    background: #303030;\n"
"    border: 1px solid rgb(64, 66, 72);\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"    border-bottom: none;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#searchFrame:hover, \n"
"#searchFrame_2:hover,\n"
"#searchFrame_3:hover\n"
"{\n"
"    border: 2px solid     #4c4c4c;\n"
"}\n"
"\n"
"#searchButtonIcon, \n"
"#searchButtonIcon_2,\n"
"#searchButtonIcon_3\n"
"{\n"
"    background-color: #303030;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"#lineEditSearchProduct,\n"
"#lineEditSearchCustomer,\n"
"#lineEditSearchOrder {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#lineEditSearchProduct:hover, #lineEditSearchProduct:focus,\n"
"#lineEditSearchCustomer:hover, #lineEditSearchCustomer:focus,\n"
"#lineEditSearchOrder:hover, #lineEditSearchOrder:focus\n"
"{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* *************************************************\n"
"        DETAILS FRAME  = QDockWidget\n"
"***************************************************/\n"
"#dockWidgetContents,\n"
"#rightFrame, \n"
"#allDetailsPage,\n"
"#createOrderPage,\n"
"#scrollAreaWidgetContents \n"
"{\n"
"    background-color: #272727;\n"
"}\n"
"\n"
"#labelTitleDetails {\n"
"    \n"
"    font: italic 15pt \"Droid Sans Fallback\";\n"
"}\n"
"\n"
"#scrollAreaWidgetContents {\n"
"    border: 2px solid #4c4c4c;\n"
"    border-bottom: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"\n"
"#titleFrame {\n"
"    border: 2px solid #4c4c4c;\n"
"    border-top: none;\n"
"    border-left: none;    \n"
"    border-right: none;\n"
"}\n"
"\n"
"/*===    Close Card Button   ===*/\n"
"#buttonCloseCard {\n"
"    border-radius: 19px;\n"
"    background: transparent;    \n"
"}\n"
"\n"
"#buttonCloseCard:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"#buttonCloseCard:pressed {\n"
"    background-color: transparent;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"/********************\n"
"    Details Frame \n"
"****************************/\n"
"\n"
"/*** Search LineEdit Button Icon ***/\n"
"/***********************\n"
"         QComboBox \n"
"************************/\n"
"\n"
"QComboBox {\n"
"    font: 12pt \"Droid Sans Fallback\";\n"
"    background-color: #32312f;\n"
"    color: #ffffff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(64, 66, 72);    \n"
"    padding: 7px;\n"
"    padding-left: 10px;\n"
"    combobox-popup: 0;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid #4c4c4c;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-right-width: 3px;\n"
"    border-right-color: #4c4c4c;\n"
"    border-right-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:/icons/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    padding: 10px;\n"
" }\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #ffffff; \n"
"    background-color: transparent;\n"
"    padding: 10px 0;\n"
"    selection-background-color: #555555;\n"
"    border: 2px solid #4c4c4c;\n"
"    border-top: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"/***************\n"
"         QTableWidget \n"
"********************************/\n"
"\n"
"QTableWidget {\n"
"    background-color: transparent;\n"
"    selection-color: #434343;\n"
"    color: #eeeeee;\n"
"    gridline-color: #323232;\n"
"    border-radius: 2;\n"
"    font: 12pt \"Droid Sans Fallback\";\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: #eeeeee;\n"
"    padding: 6 0 6 -10;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #263848;\n"
"    border-width: 1 1 1 0;\n"
"    border-style: solid;\n"
"    border-color: #1b252f;\n"
"    font: 75 12pt \"Droid Sans Fallback\";\n"
"    color: #00d4ff;\n"
"    padding-left:10;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(:/icons/icons/cil-arrow-top.png);\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    image: url(:/icons/icons/cil-arrow-bottom.png);\n"
"}\n"
"\n"
"/**************** *************\n"
"        QScrollBar \n"
"********************/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #4b7bec;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: #4b7bec;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/**********************\n"
"    => QToolTip\n"
"***********************/\n"
"QToolTip {\n"
"    background-color: #272727;\n"
"    border: 1px solid     #4c4c4c;\n"
"    padding: 0px 5px;\n"
"    color: #ffffff;\n"
"    border-radius: 10px;\n"
"    font: 12pt \"Droid Sans Fallback\";\n"
"}")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setStyleSheet("")
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuFrame = QtWidgets.QFrame(self.mainWidget)
        self.menuFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.menuFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.menuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuFrame.setObjectName("menuFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.menuFrame)
        self.horizontalLayout_9.setContentsMargins(0, 9, 0, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.buttonUsername = QtWidgets.QPushButton(self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUsername.sizePolicy().hasHeightForWidth())
        self.buttonUsername.setSizePolicy(sizePolicy)
        self.buttonUsername.setMinimumSize(QtCore.QSize(50, 50))
        self.buttonUsername.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonUsername.setFont(font)
        self.buttonUsername.setStyleSheet("")
        self.buttonUsername.setText("")
        self.buttonUsername.setIconSize(QtCore.QSize(30, 30))
        self.buttonUsername.setObjectName("buttonUsername")
        self.horizontalLayout_9.addWidget(self.buttonUsername)
        self.buttonProductPage = QtWidgets.QPushButton(self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProductPage.sizePolicy().hasHeightForWidth())
        self.buttonProductPage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonProductPage.setFont(font)
        self.buttonProductPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonProductPage.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-tags.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonProductPage.setIcon(icon)
        self.buttonProductPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonProductPage.setCheckable(True)
        self.buttonProductPage.setChecked(False)
        self.buttonProductPage.setObjectName("buttonProductPage")
        self.horizontalLayout_9.addWidget(self.buttonProductPage)
        self.buttonCustomerPage = QtWidgets.QPushButton(self.menuFrame)
        self.buttonCustomerPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-people.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonCustomerPage.setIcon(icon1)
        self.buttonCustomerPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonCustomerPage.setCheckable(True)
        self.buttonCustomerPage.setObjectName("buttonCustomerPage")
        self.horizontalLayout_9.addWidget(self.buttonCustomerPage)
        self.buttonOrderPage = QtWidgets.QPushButton(self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOrderPage.sizePolicy().hasHeightForWidth())
        self.buttonOrderPage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonOrderPage.setFont(font)
        self.buttonOrderPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOrderPage.setIcon(icon2)
        self.buttonOrderPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonOrderPage.setCheckable(True)
        self.buttonOrderPage.setChecked(False)
        self.buttonOrderPage.setObjectName("buttonOrderPage")
        self.horizontalLayout_9.addWidget(self.buttonOrderPage)
        self.buttonStatisticsPage = QtWidgets.QPushButton(self.menuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStatisticsPage.sizePolicy().hasHeightForWidth())
        self.buttonStatisticsPage.setSizePolicy(sizePolicy)
        self.buttonStatisticsPage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStatisticsPage.setIcon(icon3)
        self.buttonStatisticsPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonStatisticsPage.setCheckable(True)
        self.buttonStatisticsPage.setChecked(False)
        self.buttonStatisticsPage.setObjectName("buttonStatisticsPage")
        self.horizontalLayout_9.addWidget(self.buttonStatisticsPage)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.menuFrame)
        self.containerStackedWidget = QtWidgets.QStackedWidget(self.mainWidget)
        self.containerStackedWidget.setMinimumSize(QtCore.QSize(390, 0))
        self.containerStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.containerStackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerStackedWidget.setObjectName("containerStackedWidget")
        self.ProductPage = QtWidgets.QWidget()
        self.ProductPage.setObjectName("ProductPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ProductPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.ProductPage)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxProductBy = QtWidgets.QComboBox(self.frame)
        self.comboBoxProductBy.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxProductBy.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBoxProductBy.setFont(font)
        self.comboBoxProductBy.setObjectName("comboBoxProductBy")
        self.comboBoxProductBy.addItem("")
        self.comboBoxProductBy.addItem("")
        self.comboBoxProductBy.addItem("")
        self.comboBoxProductBy.addItem("")
        self.gridLayout.addWidget(self.comboBoxProductBy, 2, 0, 1, 1)
        self.labelErrorProductPage = QtWidgets.QLabel(self.frame)
        self.labelErrorProductPage.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelErrorProductPage.setFont(font)
        self.labelErrorProductPage.setText("")
        self.labelErrorProductPage.setObjectName("labelErrorProductPage")
        self.gridLayout.addWidget(self.labelErrorProductPage, 2, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.frameToolButton_3 = QtWidgets.QFrame(self.ProductPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton_3.sizePolicy().hasHeightForWidth())
        self.frameToolButton_3.setSizePolicy(sizePolicy)
        self.frameToolButton_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton_3.setObjectName("frameToolButton_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frameToolButton_3)
        self.horizontalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.searchFrame = QtWidgets.QFrame(self.frameToolButton_3)
        self.searchFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.searchFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_4.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchButtonIcon = QtWidgets.QPushButton(self.searchFrame)
        self.searchButtonIcon.setEnabled(False)
        self.searchButtonIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.searchButtonIcon.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButtonIcon.setIcon(icon4)
        self.searchButtonIcon.setIconSize(QtCore.QSize(25, 25))
        self.searchButtonIcon.setObjectName("searchButtonIcon")
        self.horizontalLayout_4.addWidget(self.searchButtonIcon)
        self.lineEditSearchProduct = QtWidgets.QLineEdit(self.searchFrame)
        self.lineEditSearchProduct.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSearchProduct.setFont(font)
        self.lineEditSearchProduct.setObjectName("lineEditSearchProduct")
        self.horizontalLayout_4.addWidget(self.lineEditSearchProduct)
        self.horizontalLayout_12.addWidget(self.searchFrame)
        self.labelProductTableCount = QtWidgets.QLabel(self.frameToolButton_3)
        self.labelProductTableCount.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelProductTableCount.setFont(font)
        self.labelProductTableCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProductTableCount.setObjectName("labelProductTableCount")
        self.horizontalLayout_12.addWidget(self.labelProductTableCount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.buttonProductDetails = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProductDetails.sizePolicy().hasHeightForWidth())
        self.buttonProductDetails.setSizePolicy(sizePolicy)
        self.buttonProductDetails.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonProductDetails.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonProductDetails.setText("")
        self.buttonProductDetails.setIconSize(QtCore.QSize(27, 27))
        self.buttonProductDetails.setObjectName("buttonProductDetails")
        self.horizontalLayout_12.addWidget(self.buttonProductDetails)
        self.buttonNewProduct = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNewProduct.sizePolicy().hasHeightForWidth())
        self.buttonNewProduct.setSizePolicy(sizePolicy)
        self.buttonNewProduct.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonNewProduct.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonNewProduct.setText("")
        self.buttonNewProduct.setIconSize(QtCore.QSize(27, 27))
        self.buttonNewProduct.setObjectName("buttonNewProduct")
        self.horizontalLayout_12.addWidget(self.buttonNewProduct)
        self.buttonEditProduct = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEditProduct.sizePolicy().hasHeightForWidth())
        self.buttonEditProduct.setSizePolicy(sizePolicy)
        self.buttonEditProduct.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonEditProduct.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonEditProduct.setText("")
        self.buttonEditProduct.setIconSize(QtCore.QSize(27, 27))
        self.buttonEditProduct.setObjectName("buttonEditProduct")
        self.horizontalLayout_12.addWidget(self.buttonEditProduct)
        self.buttonDeleteProduct = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteProduct.sizePolicy().hasHeightForWidth())
        self.buttonDeleteProduct.setSizePolicy(sizePolicy)
        self.buttonDeleteProduct.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDeleteProduct.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDeleteProduct.setText("")
        self.buttonDeleteProduct.setIconSize(QtCore.QSize(27, 27))
        self.buttonDeleteProduct.setObjectName("buttonDeleteProduct")
        self.horizontalLayout_12.addWidget(self.buttonDeleteProduct)
        self.verticalLayout_4.addWidget(self.frameToolButton_3)
        self.tableWidgetProduct = QtWidgets.QTableWidget(self.ProductPage)
        self.tableWidgetProduct.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetProduct.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetProduct.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetProduct.setObjectName("tableWidgetProduct")
        self.tableWidgetProduct.setColumnCount(3)
        self.tableWidgetProduct.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 2, item)
        self.tableWidgetProduct.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidgetProduct.horizontalHeader().setHighlightSections(False)
        self.tableWidgetProduct.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetProduct.verticalHeader().setVisible(False)
        self.tableWidgetProduct.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.tableWidgetProduct)
        self.containerStackedWidget.addWidget(self.ProductPage)
        self.CustomerPage = QtWidgets.QWidget()
        self.CustomerPage.setObjectName("CustomerPage")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.CustomerPage)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_3 = QtWidgets.QFrame(self.CustomerPage)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBoxProductBy_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBoxProductBy_2.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxProductBy_2.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBoxProductBy_2.setFont(font)
        self.comboBoxProductBy_2.setObjectName("comboBoxProductBy_2")
        self.comboBoxProductBy_2.addItem("")
        self.comboBoxProductBy_2.addItem("")
        self.comboBoxProductBy_2.addItem("")
        self.comboBoxProductBy_2.addItem("")
        self.gridLayout_4.addWidget(self.comboBoxProductBy_2, 2, 0, 1, 1)
        self.labelErrorCustomerPage = QtWidgets.QLabel(self.frame_3)
        self.labelErrorCustomerPage.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelErrorCustomerPage.setFont(font)
        self.labelErrorCustomerPage.setText("")
        self.labelErrorCustomerPage.setObjectName("labelErrorCustomerPage")
        self.gridLayout_4.addWidget(self.labelErrorCustomerPage, 2, 3, 1, 1)
        self.verticalLayout_19.addWidget(self.frame_3)
        self.frameToolButton_4 = QtWidgets.QFrame(self.CustomerPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton_4.sizePolicy().hasHeightForWidth())
        self.frameToolButton_4.setSizePolicy(sizePolicy)
        self.frameToolButton_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton_4.setObjectName("frameToolButton_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frameToolButton_4)
        self.horizontalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.searchFrame_3 = QtWidgets.QFrame(self.frameToolButton_4)
        self.searchFrame_3.setMinimumSize(QtCore.QSize(200, 0))
        self.searchFrame_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.searchFrame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame_3.setObjectName("searchFrame_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.searchFrame_3)
        self.horizontalLayout_14.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.searchButtonIcon_3 = QtWidgets.QPushButton(self.searchFrame_3)
        self.searchButtonIcon_3.setEnabled(False)
        self.searchButtonIcon_3.setMinimumSize(QtCore.QSize(0, 0))
        self.searchButtonIcon_3.setText("")
        self.searchButtonIcon_3.setIcon(icon4)
        self.searchButtonIcon_3.setIconSize(QtCore.QSize(25, 25))
        self.searchButtonIcon_3.setObjectName("searchButtonIcon_3")
        self.horizontalLayout_14.addWidget(self.searchButtonIcon_3)
        self.lineEditSearchCustomer = QtWidgets.QLineEdit(self.searchFrame_3)
        self.lineEditSearchCustomer.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSearchCustomer.setFont(font)
        self.lineEditSearchCustomer.setObjectName("lineEditSearchCustomer")
        self.horizontalLayout_14.addWidget(self.lineEditSearchCustomer)
        self.horizontalLayout_13.addWidget(self.searchFrame_3)
        self.labelCustomerTableCount = QtWidgets.QLabel(self.frameToolButton_4)
        self.labelCustomerTableCount.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelCustomerTableCount.setFont(font)
        self.labelCustomerTableCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCustomerTableCount.setObjectName("labelCustomerTableCount")
        self.horizontalLayout_13.addWidget(self.labelCustomerTableCount)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        self.buttonCustomerDetails = QtWidgets.QPushButton(self.frameToolButton_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCustomerDetails.sizePolicy().hasHeightForWidth())
        self.buttonCustomerDetails.setSizePolicy(sizePolicy)
        self.buttonCustomerDetails.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonCustomerDetails.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonCustomerDetails.setText("")
        self.buttonCustomerDetails.setIconSize(QtCore.QSize(27, 27))
        self.buttonCustomerDetails.setObjectName("buttonCustomerDetails")
        self.horizontalLayout_13.addWidget(self.buttonCustomerDetails)
        self.buttonNewCustomer = QtWidgets.QPushButton(self.frameToolButton_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNewCustomer.sizePolicy().hasHeightForWidth())
        self.buttonNewCustomer.setSizePolicy(sizePolicy)
        self.buttonNewCustomer.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonNewCustomer.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonNewCustomer.setText("")
        self.buttonNewCustomer.setIconSize(QtCore.QSize(27, 27))
        self.buttonNewCustomer.setObjectName("buttonNewCustomer")
        self.horizontalLayout_13.addWidget(self.buttonNewCustomer)
        self.buttonEditCustomer = QtWidgets.QPushButton(self.frameToolButton_4)
        self.buttonEditCustomer.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEditCustomer.sizePolicy().hasHeightForWidth())
        self.buttonEditCustomer.setSizePolicy(sizePolicy)
        self.buttonEditCustomer.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonEditCustomer.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonEditCustomer.setText("")
        self.buttonEditCustomer.setIconSize(QtCore.QSize(27, 27))
        self.buttonEditCustomer.setObjectName("buttonEditCustomer")
        self.horizontalLayout_13.addWidget(self.buttonEditCustomer)
        self.buttonDeleteCustomer = QtWidgets.QPushButton(self.frameToolButton_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteCustomer.sizePolicy().hasHeightForWidth())
        self.buttonDeleteCustomer.setSizePolicy(sizePolicy)
        self.buttonDeleteCustomer.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDeleteCustomer.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDeleteCustomer.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDeleteCustomer.setIcon(icon5)
        self.buttonDeleteCustomer.setIconSize(QtCore.QSize(27, 27))
        self.buttonDeleteCustomer.setObjectName("buttonDeleteCustomer")
        self.horizontalLayout_13.addWidget(self.buttonDeleteCustomer)
        self.verticalLayout_19.addWidget(self.frameToolButton_4)
        self.tableWidgetCustomer = QtWidgets.QTableWidget(self.CustomerPage)
        self.tableWidgetCustomer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetCustomer.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetCustomer.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetCustomer.setObjectName("tableWidgetCustomer")
        self.tableWidgetCustomer.setColumnCount(3)
        self.tableWidgetCustomer.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setItem(1, 2, item)
        self.tableWidgetCustomer.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidgetCustomer.horizontalHeader().setHighlightSections(False)
        self.tableWidgetCustomer.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetCustomer.verticalHeader().setVisible(False)
        self.tableWidgetCustomer.verticalHeader().setHighlightSections(False)
        self.verticalLayout_19.addWidget(self.tableWidgetCustomer)
        self.containerStackedWidget.addWidget(self.CustomerPage)
        self.OrderPage = QtWidgets.QWidget()
        self.OrderPage.setObjectName("OrderPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.OrderPage)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_2 = QtWidgets.QFrame(self.OrderPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelErrorOrderPage = QtWidgets.QLabel(self.frame_2)
        self.labelErrorOrderPage.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelErrorOrderPage.setFont(font)
        self.labelErrorOrderPage.setText("")
        self.labelErrorOrderPage.setObjectName("labelErrorOrderPage")
        self.gridLayout_3.addWidget(self.labelErrorOrderPage, 3, 3, 1, 1)
        self.comboBoxOrderBy = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxOrderBy.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxOrderBy.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBoxOrderBy.setFont(font)
        self.comboBoxOrderBy.setObjectName("comboBoxOrderBy")
        self.comboBoxOrderBy.addItem("")
        self.comboBoxOrderBy.addItem("")
        self.comboBoxOrderBy.addItem("")
        self.comboBoxOrderBy.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxOrderBy, 3, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_2)
        self.frameToolButton = QtWidgets.QFrame(self.OrderPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton.sizePolicy().hasHeightForWidth())
        self.frameToolButton.setSizePolicy(sizePolicy)
        self.frameToolButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton.setObjectName("frameToolButton")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frameToolButton)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.searchFrame_2 = QtWidgets.QFrame(self.frameToolButton)
        self.searchFrame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.searchFrame_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.searchFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame_2.setObjectName("searchFrame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.searchFrame_2)
        self.horizontalLayout_10.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.searchButtonIcon_2 = QtWidgets.QPushButton(self.searchFrame_2)
        self.searchButtonIcon_2.setEnabled(False)
        self.searchButtonIcon_2.setMinimumSize(QtCore.QSize(0, 0))
        self.searchButtonIcon_2.setText("")
        self.searchButtonIcon_2.setIcon(icon4)
        self.searchButtonIcon_2.setIconSize(QtCore.QSize(25, 25))
        self.searchButtonIcon_2.setObjectName("searchButtonIcon_2")
        self.horizontalLayout_10.addWidget(self.searchButtonIcon_2)
        self.lineEditSearchOrder = QtWidgets.QLineEdit(self.searchFrame_2)
        self.lineEditSearchOrder.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEditSearchOrder.setFont(font)
        self.lineEditSearchOrder.setObjectName("lineEditSearchOrder")
        self.horizontalLayout_10.addWidget(self.lineEditSearchOrder)
        self.horizontalLayout_5.addWidget(self.searchFrame_2)
        self.labelOrderTableCount = QtWidgets.QLabel(self.frameToolButton)
        self.labelOrderTableCount.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Thai")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelOrderTableCount.setFont(font)
        self.labelOrderTableCount.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOrderTableCount.setObjectName("labelOrderTableCount")
        self.horizontalLayout_5.addWidget(self.labelOrderTableCount)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.buttonNewOrder = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNewOrder.sizePolicy().hasHeightForWidth())
        self.buttonNewOrder.setSizePolicy(sizePolicy)
        self.buttonNewOrder.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonNewOrder.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonNewOrder.setText("")
        self.buttonNewOrder.setIconSize(QtCore.QSize(27, 27))
        self.buttonNewOrder.setObjectName("buttonNewOrder")
        self.horizontalLayout_5.addWidget(self.buttonNewOrder)
        self.buttonOrderDetails = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOrderDetails.sizePolicy().hasHeightForWidth())
        self.buttonOrderDetails.setSizePolicy(sizePolicy)
        self.buttonOrderDetails.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonOrderDetails.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonOrderDetails.setText("")
        self.buttonOrderDetails.setIconSize(QtCore.QSize(27, 27))
        self.buttonOrderDetails.setObjectName("buttonOrderDetails")
        self.horizontalLayout_5.addWidget(self.buttonOrderDetails)
        self.buttonDeleteOrder = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteOrder.sizePolicy().hasHeightForWidth())
        self.buttonDeleteOrder.setSizePolicy(sizePolicy)
        self.buttonDeleteOrder.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDeleteOrder.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDeleteOrder.setText("")
        self.buttonDeleteOrder.setIconSize(QtCore.QSize(27, 27))
        self.buttonDeleteOrder.setObjectName("buttonDeleteOrder")
        self.horizontalLayout_5.addWidget(self.buttonDeleteOrder)
        self.verticalLayout_15.addWidget(self.frameToolButton)
        self.tableWidgetOrders = QtWidgets.QTableWidget(self.OrderPage)
        self.tableWidgetOrders.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetOrders.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetOrders.setObjectName("tableWidgetOrders")
        self.tableWidgetOrders.setColumnCount(3)
        self.tableWidgetOrders.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(1, 2, item)
        self.tableWidgetOrders.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidgetOrders.horizontalHeader().setHighlightSections(False)
        self.tableWidgetOrders.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetOrders.verticalHeader().setVisible(False)
        self.tableWidgetOrders.verticalHeader().setHighlightSections(False)
        self.verticalLayout_15.addWidget(self.tableWidgetOrders)
        self.containerStackedWidget.addWidget(self.OrderPage)
        self.statisticsPage = QtWidgets.QWidget()
        self.statisticsPage.setObjectName("statisticsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.statisticsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 116, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.stackedWidgetInfoCard = QtWidgets.QStackedWidget(self.statisticsPage)
        self.stackedWidgetInfoCard.setMinimumSize(QtCore.QSize(0, 350))
        self.stackedWidgetInfoCard.setStyleSheet("")
        self.stackedWidgetInfoCard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidgetInfoCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidgetInfoCard.setObjectName("stackedWidgetInfoCard")
        self.stWidgetInfoPage = QtWidgets.QWidget()
        self.stWidgetInfoPage.setObjectName("stWidgetInfoPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.stWidgetInfoPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridFrame = QtWidgets.QFrame(self.stWidgetInfoPage)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.gridFrame)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/cil-clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon6)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gridFrame)
        self.tableWidgetProcessConnections = QtWidgets.QTableWidget(self.stWidgetInfoPage)
        self.tableWidgetProcessConnections.setObjectName("tableWidgetProcessConnections")
        self.tableWidgetProcessConnections.setColumnCount(0)
        self.tableWidgetProcessConnections.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidgetProcessConnections)
        self.stackedWidgetInfoCard.addWidget(self.stWidgetInfoPage)
        self.stWidgetOsInfoPage = QtWidgets.QWidget()
        self.stWidgetOsInfoPage.setMaximumSize(QtCore.QSize(800, 16777215))
        self.stWidgetOsInfoPage.setObjectName("stWidgetOsInfoPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.stWidgetOsInfoPage)
        self.verticalLayout_14.setSpacing(15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelName = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelName.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelName.setObjectName("labelName")
        self.verticalLayout_8.addWidget(self.labelName)
        self.labelNameValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelNameValue.setObjectName("labelNameValue")
        self.verticalLayout_8.addWidget(self.labelNameValue)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelVersion = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelVersion.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelVersion.setObjectName("labelVersion")
        self.verticalLayout_9.addWidget(self.labelVersion)
        self.labelVersionValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelVersionValue.setObjectName("labelVersionValue")
        self.verticalLayout_9.addWidget(self.labelVersionValue)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelPlatform = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelPlatform.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelPlatform.setObjectName("labelPlatform")
        self.verticalLayout_10.addWidget(self.labelPlatform)
        self.labelPlatformValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelPlatformValue.setObjectName("labelPlatformValue")
        self.verticalLayout_10.addWidget(self.labelPlatformValue)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.labelArch = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelArch.setFont(font)
        self.labelArch.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelArch.setObjectName("labelArch")
        self.verticalLayout_11.addWidget(self.labelArch)
        self.labelArchValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelArchValue.setObjectName("labelArchValue")
        self.verticalLayout_11.addWidget(self.labelArchValue)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.labelCpu = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelCpu.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelCpu.setObjectName("labelCpu")
        self.verticalLayout_12.addWidget(self.labelCpu)
        self.labelCpuValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelCpuValue.setObjectName("labelCpuValue")
        self.verticalLayout_12.addWidget(self.labelCpuValue)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelRam = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelRam.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelRam.setObjectName("labelRam")
        self.verticalLayout_13.addWidget(self.labelRam)
        self.labelRamValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelRamValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelRamValue.setObjectName("labelRamValue")
        self.verticalLayout_13.addWidget(self.labelRamValue)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem7)
        self.stackedWidgetInfoCard.addWidget(self.stWidgetOsInfoPage)
        self.verticalLayout_6.addWidget(self.stackedWidgetInfoCard)
        spacerItem8 = QtWidgets.QSpacerItem(20, 116, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.containerStackedWidget.addWidget(self.statisticsPage)
        self.verticalLayout_2.addWidget(self.containerStackedWidget)
        self.verticalLayout_18.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rightFrame = QtWidgets.QFrame(self.dockWidgetContents)
        self.rightFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.rightFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleFrame = QtWidgets.QFrame(self.rightFrame)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCloseCard = QtWidgets.QPushButton(self.titleFrame)
        self.buttonCloseCard.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonCloseCard.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonCloseCard.setText("")
        self.buttonCloseCard.setIconSize(QtCore.QSize(25, 25))
        self.buttonCloseCard.setObjectName("buttonCloseCard")
        self.horizontalLayout_2.addWidget(self.buttonCloseCard)
        self.labelTitleDetails = QtWidgets.QLabel(self.titleFrame)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelTitleDetails.setFont(font)
        self.labelTitleDetails.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitleDetails.setWordWrap(True)
        self.labelTitleDetails.setObjectName("labelTitleDetails")
        self.horizontalLayout_2.addWidget(self.labelTitleDetails)
        self.verticalLayout_3.addWidget(self.titleFrame)
        self.frameToolButton_2 = QtWidgets.QFrame(self.rightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton_2.sizePolicy().hasHeightForWidth())
        self.frameToolButton_2.setSizePolicy(sizePolicy)
        self.frameToolButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton_2.setObjectName("frameToolButton_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frameToolButton_2)
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.buttonSave = QtWidgets.QPushButton(self.frameToolButton_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSave.sizePolicy().hasHeightForWidth())
        self.buttonSave.setSizePolicy(sizePolicy)
        self.buttonSave.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonSave.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonSave.setText("")
        self.buttonSave.setIconSize(QtCore.QSize(27, 27))
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout_11.addWidget(self.buttonSave)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout_3.addWidget(self.frameToolButton_2)
        self.stackedWidgetDetails = QtWidgets.QStackedWidget(self.rightFrame)
        self.stackedWidgetDetails.setObjectName("stackedWidgetDetails")
        self.allDetailsPage = QtWidgets.QWidget()
        self.allDetailsPage.setObjectName("allDetailsPage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.allDetailsPage)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.scrollArea = QtWidgets.QScrollArea(self.allDetailsPage)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 454))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frameDetailsID = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameDetailsID.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameDetailsID.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDetailsID.setObjectName("frameDetailsID")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameDetailsID)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelOperation = QtWidgets.QLabel(self.frameDetailsID)
        self.labelOperation.setText("")
        self.labelOperation.setObjectName("labelOperation")
        self.horizontalLayout_8.addWidget(self.labelOperation)
        self.labelItemID = QtWidgets.QLabel(self.frameDetailsID)
        self.labelItemID.setText("")
        self.labelItemID.setObjectName("labelItemID")
        self.horizontalLayout_8.addWidget(self.labelItemID)
        self.labelMongoTable = QtWidgets.QLabel(self.frameDetailsID)
        self.labelMongoTable.setText("")
        self.labelMongoTable.setObjectName("labelMongoTable")
        self.horizontalLayout_8.addWidget(self.labelMongoTable)
        self.verticalLayout_5.addWidget(self.frameDetailsID)
        self.formFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy)
        self.formFrame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.formFrame)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lineEdit)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.formFrame)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.verticalLayout_5.addWidget(self.formFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_16.addWidget(self.scrollArea)
        self.stackedWidgetDetails.addWidget(self.allDetailsPage)
        self.createOrderPage = QtWidgets.QWidget()
        self.createOrderPage.setObjectName("createOrderPage")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.createOrderPage)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frameNewOrderForm = QtWidgets.QFrame(self.createOrderPage)
        self.frameNewOrderForm.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameNewOrderForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNewOrderForm.setObjectName("frameNewOrderForm")
        self.formLayoutNewOrder = QtWidgets.QFormLayout(self.frameNewOrderForm)
        self.formLayoutNewOrder.setContentsMargins(0, -1, 0, -1)
        self.formLayoutNewOrder.setObjectName("formLayoutNewOrder")
        self.label = QtWidgets.QLabel(self.frameNewOrderForm)
        self.label.setObjectName("label")
        self.formLayoutNewOrder.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBoxAddOrderCustomer_id = QtWidgets.QComboBox(self.frameNewOrderForm)
        self.comboBoxAddOrderCustomer_id.setObjectName("comboBoxAddOrderCustomer_id")
        self.formLayoutNewOrder.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxAddOrderCustomer_id)
        self.label_2 = QtWidgets.QLabel(self.frameNewOrderForm)
        self.label_2.setObjectName("label_2")
        self.formLayoutNewOrder.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBoxAddOrderStatus = QtWidgets.QComboBox(self.frameNewOrderForm)
        self.comboBoxAddOrderStatus.setObjectName("comboBoxAddOrderStatus")
        self.formLayoutNewOrder.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxAddOrderStatus)
        self.label_3 = QtWidgets.QLabel(self.frameNewOrderForm)
        self.label_3.setObjectName("label_3")
        self.formLayoutNewOrder.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.dateEditAddOrderDate = QtWidgets.QDateEdit(self.frameNewOrderForm)
        self.dateEditAddOrderDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEditAddOrderDate.setCalendarPopup(False)
        self.dateEditAddOrderDate.setObjectName("dateEditAddOrderDate")
        self.formLayoutNewOrder.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEditAddOrderDate)
        self.label_4 = QtWidgets.QLabel(self.frameNewOrderForm)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.formLayoutNewOrder.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.buttonAddToCart = QtWidgets.QPushButton(self.frameNewOrderForm)
        self.buttonAddToCart.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.buttonAddToCart.setObjectName("buttonAddToCart")
        self.formLayoutNewOrder.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.buttonAddToCart)
        self.tableWidgetAddOrderProds = QtWidgets.QTableWidget(self.frameNewOrderForm)
        self.tableWidgetAddOrderProds.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetAddOrderProds.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetAddOrderProds.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetAddOrderProds.setObjectName("tableWidgetAddOrderProds")
        self.tableWidgetAddOrderProds.setColumnCount(0)
        self.tableWidgetAddOrderProds.setRowCount(0)
        self.tableWidgetAddOrderProds.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetAddOrderProds.verticalHeader().setVisible(False)
        self.tableWidgetAddOrderProds.verticalHeader().setDefaultSectionSize(50)
        self.formLayoutNewOrder.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tableWidgetAddOrderProds)
        self.labelMontajatNedForColData = QtWidgets.QLabel(self.frameNewOrderForm)
        self.labelMontajatNedForColData.setText("")
        self.labelMontajatNedForColData.setObjectName("labelMontajatNedForColData")
        self.formLayoutNewOrder.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelMontajatNedForColData)
        self.verticalLayout_17.addWidget(self.frameNewOrderForm)
        spacerItem10 = QtWidgets.QSpacerItem(20, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem10)
        self.stackedWidgetDetails.addWidget(self.createOrderPage)
        self.verticalLayout_3.addWidget(self.stackedWidgetDetails)
        self.verticalLayout.addWidget(self.rightFrame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.containerStackedWidget.setCurrentIndex(2)
        self.stackedWidgetInfoCard.setCurrentIndex(0)
        self.stackedWidgetDetails.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonProductPage.setText(_translate("MainWindow", "السلعة"))
        self.buttonCustomerPage.setText(_translate("MainWindow", "المشترية"))
        self.buttonOrderPage.setText(_translate("MainWindow", "الطلبيات"))
        self.buttonStatisticsPage.setText(_translate("MainWindow", "الإحصائيات"))
        self.comboBoxProductBy.setStatusTip(_translate("MainWindow", "Process By Owner"))
        self.comboBoxProductBy.setPlaceholderText(_translate("MainWindow", "Process By Username"))
        self.comboBoxProductBy.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy.setItemText(3, _translate("MainWindow", "New Item"))
        self.lineEditSearchProduct.setToolTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchProduct.setStatusTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchProduct.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.labelProductTableCount.setText(_translate("MainWindow", "المجموع"))
        self.buttonProductDetails.setToolTip(_translate("MainWindow", "معلومات إضافية عن السلعة"))
        self.buttonProductDetails.setStatusTip(_translate("MainWindow", "معلومات إضافية عن السلعة"))
        self.buttonNewProduct.setToolTip(_translate("MainWindow", "إضافة سلعة"))
        self.buttonNewProduct.setStatusTip(_translate("MainWindow", "إضافة سلعة"))
        self.buttonEditProduct.setToolTip(_translate("MainWindow", "تعديل على السلعة"))
        self.buttonEditProduct.setStatusTip(_translate("MainWindow", "تعديل على السلعة"))
        self.buttonDeleteProduct.setToolTip(_translate("MainWindow", "حذف السلعة"))
        self.buttonDeleteProduct.setStatusTip(_translate("MainWindow", "حذف السلعة"))
        self.tableWidgetProduct.setSortingEnabled(True)
        item = self.tableWidgetProduct.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PID"))
        item = self.tableWidgetProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAM"))
        item = self.tableWidgetProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        __sortingEnabled = self.tableWidgetProduct.isSortingEnabled()
        self.tableWidgetProduct.setSortingEnabled(False)
        item = self.tableWidgetProduct.item(0, 0)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetProduct.item(0, 1)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetProduct.item(0, 2)
        item.setText(_translate("MainWindow", "runing"))
        item = self.tableWidgetProduct.item(1, 0)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetProduct.item(1, 1)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetProduct.item(1, 2)
        item.setText(_translate("MainWindow", "runing"))
        self.tableWidgetProduct.setSortingEnabled(__sortingEnabled)
        self.comboBoxProductBy_2.setStatusTip(_translate("MainWindow", "Process By Owner"))
        self.comboBoxProductBy_2.setPlaceholderText(_translate("MainWindow", "Process By Username"))
        self.comboBoxProductBy_2.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy_2.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy_2.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy_2.setItemText(3, _translate("MainWindow", "New Item"))
        self.lineEditSearchCustomer.setToolTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchCustomer.setStatusTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchCustomer.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.labelCustomerTableCount.setText(_translate("MainWindow", "المجموع"))
        self.buttonCustomerDetails.setToolTip(_translate("MainWindow", "معلومات إضافية عن السلعة"))
        self.buttonCustomerDetails.setStatusTip(_translate("MainWindow", "معلومات إضافية عن السلعة"))
        self.buttonNewCustomer.setToolTip(_translate("MainWindow", "إضافة مشتري"))
        self.buttonNewCustomer.setStatusTip(_translate("MainWindow", "إضافة مشتري"))
        self.buttonEditCustomer.setToolTip(_translate("MainWindow", "تعديل"))
        self.buttonEditCustomer.setStatusTip(_translate("MainWindow", "تعديل"))
        self.buttonDeleteCustomer.setToolTip(_translate("MainWindow", "حذف المشتري"))
        self.buttonDeleteCustomer.setStatusTip(_translate("MainWindow", "حذف المشتري"))
        self.tableWidgetCustomer.setSortingEnabled(True)
        item = self.tableWidgetCustomer.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCustomer.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCustomer.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCustomer.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCustomer.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCustomer.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PID"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAM"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        __sortingEnabled = self.tableWidgetCustomer.isSortingEnabled()
        self.tableWidgetCustomer.setSortingEnabled(False)
        item = self.tableWidgetCustomer.item(0, 0)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetCustomer.item(0, 1)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetCustomer.item(0, 2)
        item.setText(_translate("MainWindow", "runing"))
        item = self.tableWidgetCustomer.item(1, 0)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetCustomer.item(1, 1)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetCustomer.item(1, 2)
        item.setText(_translate("MainWindow", "runing"))
        self.tableWidgetCustomer.setSortingEnabled(__sortingEnabled)
        self.comboBoxOrderBy.setStatusTip(_translate("MainWindow", "Process By Owner"))
        self.comboBoxOrderBy.setPlaceholderText(_translate("MainWindow", "Process By Username"))
        self.comboBoxOrderBy.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBoxOrderBy.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBoxOrderBy.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBoxOrderBy.setItemText(3, _translate("MainWindow", "New Item"))
        self.lineEditSearchOrder.setToolTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchOrder.setStatusTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchOrder.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.labelOrderTableCount.setText(_translate("MainWindow", "المجموع"))
        self.buttonNewOrder.setToolTip(_translate("MainWindow", "طلبية جديدة"))
        self.buttonNewOrder.setStatusTip(_translate("MainWindow", "طلبية جديدة"))
        self.buttonOrderDetails.setToolTip(_translate("MainWindow", "معلومات إضافية"))
        self.buttonOrderDetails.setStatusTip(_translate("MainWindow", "معلومات إضافية"))
        self.buttonDeleteOrder.setToolTip(_translate("MainWindow", "حذف الطلبية"))
        self.buttonDeleteOrder.setStatusTip(_translate("MainWindow", "حذف الطلبية"))
        self.tableWidgetOrders.setSortingEnabled(True)
        item = self.tableWidgetOrders.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PID"))
        item = self.tableWidgetOrders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAM"))
        item = self.tableWidgetOrders.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        __sortingEnabled = self.tableWidgetOrders.isSortingEnabled()
        self.tableWidgetOrders.setSortingEnabled(False)
        item = self.tableWidgetOrders.item(0, 0)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetOrders.item(0, 1)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetOrders.item(0, 2)
        item.setText(_translate("MainWindow", "runing"))
        item = self.tableWidgetOrders.item(1, 0)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetOrders.item(1, 1)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetOrders.item(1, 2)
        item.setText(_translate("MainWindow", "runing"))
        self.tableWidgetOrders.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Copy "))
        self.labelName.setText(_translate("MainWindow", "Name"))
        self.labelNameValue.setText(_translate("MainWindow", "Value"))
        self.labelVersion.setText(_translate("MainWindow", "Version"))
        self.labelVersionValue.setText(_translate("MainWindow", "Value"))
        self.labelPlatform.setText(_translate("MainWindow", "Platform"))
        self.labelPlatformValue.setText(_translate("MainWindow", "Value"))
        self.labelArch.setText(_translate("MainWindow", "Architecture"))
        self.labelArchValue.setText(_translate("MainWindow", "Value"))
        self.labelCpu.setText(_translate("MainWindow", "Cpu"))
        self.labelCpuValue.setText(_translate("MainWindow", "Value"))
        self.labelRam.setText(_translate("MainWindow", "Ram"))
        self.labelRamValue.setText(_translate("MainWindow", "Value"))
        self.labelTitleDetails.setText(_translate("MainWindow", "معلومات إضافية"))
        self.buttonSave.setToolTip(_translate("MainWindow", "حفظ البيانات"))
        self.buttonSave.setStatusTip(_translate("MainWindow", "حفظ البيانات"))
        self.label.setText(_translate("MainWindow", "إسم العميل"))
        self.label_2.setText(_translate("MainWindow", "الحالة"))
        self.label_3.setText(_translate("MainWindow", "تاريخ الطلب"))
        self.buttonAddToCart.setText(_translate("MainWindow", "إضافة منتج"))
import resource_rc
