# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1147, 640)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet("#mainWidget {\n"
"    background-color: #2c2c2c;\n"
"}\n"
"\n"
"#ProductPage, #OrderPage, #statisticsPage {\n"
"    background: transparent;\n"
"}\n"
"/* ------- Global ---------*/\n"
"\n"
"QLabel {\n"
"    font: italic 12pt \"Droid Sans Fallback\";\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    width: 2px;\n"
"    background-color: #4c4c4c;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: brown;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QStatusBar QLabel {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border: 1px solid red;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton {    \n"
"    font: 13pt \"Droid Sans Fallback\";\n"
"}\n"
"\n"
"QLineEdit {\n"
"    font: italic 12pt \"Droid Sans Fallback\";\n"
"    background: transparent;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* ****************\n"
"     MENU FRAME \n"
"**************************/\n"
"\n"
"#leftMenuFrame {\n"
"    background-color: #303030;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #202020;\n"
"    padding: 0px 5px;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton {\n"
"    background-color: transparent;\n"
"    padding: 8px;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    text-align: right;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#leftMenuFrame QPushButton:checked {\n"
"    background-color: #454545;\n"
"}\n"
"\n"
"#leftMenuFrame #buttonUsername {\n"
"    font-size: 12pt;\n"
"    background-color: rgba(34, 112, 147, 236);\n"
"    border-radius: 42px;\n"
"    padding: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"/****************\n"
"**    Os Info Page\n"
"******************************/\n"
"#cardInfoPage, #stWidgetInfoPage, #stWidgetOsInfoPage {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#stWidgetInfoPage, #stWidgetOsInfoPage {\n"
"    background-color: #272727;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #383838;\n"
"}\n"
"\n"
"#stWidgetInfoPage QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"    font-size: 10pt;\n"
"    padding: 10px 15px;\n"
"}\n"
"\n"
"#stWidgetInfoPage QPushButton:hover {\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"#stWidgetInfoPage QPushButton:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"#labelName, #labelVersion, \n"
"#labelPlatform, #labelArch,\n"
" #labelCpu, #labelRam {    \n"
"    font: 11pt \"Ubuntu\";\n"
"    color: #8b8b8b;\n"
"}\n"
"\n"
"#labelNameValue, #labelVersionValue, \n"
"#labelPlatformValue, #labelArchValue,\n"
"#labelCpuValue, #labelRamValue \n"
"{        \n"
"    font: 16pt \"Ubuntu\";\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/****************\n"
"**    PRODUCT PAGE\n"
"******************************/\n"
"#searchFrame, #searchFrame_2 {\n"
"    background: transparent;\n"
"    border: 1px solid rgb(64, 66, 72);\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"#searchFrame:hover, #searchFrame_2 {\n"
"    border-bottom: 2px solid rgb(178, 178, 178);\n"
"}\n"
"\n"
"#searchButtonIcon, #searchButtonIcon_2 {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#labelErrorProductPage, #labelErrorOrderPage {\n"
"    color: rgb(192, 28, 40)\n"
"}\n"
"\n"
"/* *************************************************\n"
"        DETAILS FRAME  = QDockWidget\n"
"***************************************************/\n"
"\n"
"#dockWidgetContents,  #rightFrame, #scrollAreaWidgetContents {\n"
"    background-color: #272727;\n"
"}\n"
"\n"
"/*** \n"
"border-color: #4c4c4c;\n"
"*****/\n"
"\n"
"#labelTitle {\n"
"    \n"
"    font: italic 15pt \"Droid Sans Fallback\";\n"
"}\n"
"\n"
"/*===    Close Card Button   ===*/\n"
"\n"
"#scrollAreaWidgetContents {\n"
"    border: 2px solid #4c4c4c;\n"
"    border-bottom: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"\n"
"#titleFrame {\n"
"    border: 2px solid #4c4c4c;\n"
"    border-top: none;\n"
"    border-left: none;    \n"
"    border-right: none;\n"
"}\n"
"\n"
"#buttonCloseCard {\n"
"    border-radius: 19px;\n"
"    background: transparent;    \n"
"}\n"
"\n"
"#buttonCloseCard:hover {\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"#buttonCloseCard:pressed {\n"
"    background-color: transparent;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"/*** Details Frame ***/\n"
"#formFrame QLineEdit:enabled \n"
"{\n"
"    background-color: rgba(51, 50, 50, 172);\n"
"    border-bottom: 2px solid     #4c4c4c;\n"
"}\n"
"\n"
"#formFrame QLineEdit:focus\n"
"{\n"
"    border-bottom: 2px solid rgb(178, 178, 178);\n"
"}\n"
"\n"
"\n"
"#frameToolButton QPushButton, \n"
"#frameToolButton_2 QPushButton,\n"
"#frameToolButton_3 QPushButton \n"
"{\n"
"    background: transparent;\n"
"    border-radius: 5px;\n"
"    color: #ffffff;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#frameToolButton QPushButton:hover, \n"
"#frameToolButton_2 QPushButton:hover ,\n"
"#frameToolButton_3 QPushButton:hover\n"
"{\n"
"    background-color: #3e3e3e;\n"
"}\n"
"\n"
"#frameToolButton QPushButton:pressed,\n"
"#frameToolButton_2 QPushButton:pressed,\n"
"#frameToolButton_3 QPushButton:pressed\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"\n"
"\n"
"/*----------------> QComboBox <---------------------*/\n"
"\n"
"QComboBox {\n"
"    font: italic 12pt \"Droid Sans Fallback\";\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(64, 66, 72);    \n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    combobox-popup: 0;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-right-width: 3px;\n"
"    border-right-color: rgb(64, 66, 72);\n"
"    border-right-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:/icons/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #4b7bec; /*rgb(255, 121, 198);    */\n"
"    background-color: transparent;\n"
"    padding: 10px 7px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"    border-top: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 12px;\n"
"}\n"
"\n"
"/***************\n"
"         QTableWidget \n"
"********************************/\n"
"\n"
"QTableWidget {\n"
"    background-color: transparent;\n"
"    selection-color: #434343;\n"
"    color: #eeeeee;\n"
"    gridline-color: #323232;\n"
"    border-radius: 2;\n"
"    font: 12pt \"Droid Sans Fallback\";\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    color: #eeeeee;\n"
"    padding: 6 0 6 -10;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #3d3d3d;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #263848;\n"
"    border-width: 1 1 1 0;\n"
"    border-style: solid;\n"
"    border-color: #1b252f;\n"
"    font: 75 12pt \"Droid Sans Fallback\";\n"
"    color: #00d4ff;\n"
"    padding-left:10;\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(:/icons/icons/cil-arrow-top.png);\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"    image: url(:/icons/icons/cil-arrow-bottom.png);\n"
"}\n"
"\n"
"/**************** QScrollBar ****************/\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #4b7bec;\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: #4b7bec;\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
"/**********************\n"
"    => QScrollBar\n"
"***********************/\n"
"/* \n"
"QScrollBar:vertical {\n"
"    width: 12;\n"
"    margin: 0 0 0 2;\n"
"    border-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: @color01;\n"
"    min-height: 20px;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    border-bottom-right-radius: 2;\n"
"    border-bottom-left-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 12;\n"
"    margin: 2 0 0 0;\n"
"    border-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: @color01;\n"
"    min-width: 20px;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    border-bottom-right-radius: 2;\n"
"    border-bottom-left-radius: 2;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    background: transparent;\n"
"}\n"
"*/")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setStyleSheet("")
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenuFrame = QtWidgets.QFrame(self.mainWidget)
        self.leftMenuFrame.setMinimumSize(QtCore.QSize(255, 0))
        self.leftMenuFrame.setMaximumSize(QtCore.QSize(273, 500))
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonUsername = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUsername.sizePolicy().hasHeightForWidth())
        self.buttonUsername.setSizePolicy(sizePolicy)
        self.buttonUsername.setMinimumSize(QtCore.QSize(84, 84))
        self.buttonUsername.setMaximumSize(QtCore.QSize(84, 84))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonUsername.setFont(font)
        self.buttonUsername.setStyleSheet("")
        self.buttonUsername.setIconSize(QtCore.QSize(30, 30))
        self.buttonUsername.setObjectName("buttonUsername")
        self.verticalLayout_2.addWidget(self.buttonUsername, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.buttonProductPage = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProductPage.sizePolicy().hasHeightForWidth())
        self.buttonProductPage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonProductPage.setFont(font)
        self.buttonProductPage.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-tags.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonProductPage.setIcon(icon)
        self.buttonProductPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonProductPage.setCheckable(True)
        self.buttonProductPage.setChecked(False)
        self.buttonProductPage.setObjectName("buttonProductPage")
        self.verticalLayout_2.addWidget(self.buttonProductPage)
        self.buttonOrderPage = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOrderPage.sizePolicy().hasHeightForWidth())
        self.buttonOrderPage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.buttonOrderPage.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-cart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonOrderPage.setIcon(icon1)
        self.buttonOrderPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonOrderPage.setCheckable(True)
        self.buttonOrderPage.setChecked(False)
        self.buttonOrderPage.setObjectName("buttonOrderPage")
        self.verticalLayout_2.addWidget(self.buttonOrderPage)
        self.buttonStatisticsPage = QtWidgets.QPushButton(self.leftMenuFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStatisticsPage.sizePolicy().hasHeightForWidth())
        self.buttonStatisticsPage.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-chart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonStatisticsPage.setIcon(icon2)
        self.buttonStatisticsPage.setIconSize(QtCore.QSize(30, 30))
        self.buttonStatisticsPage.setObjectName("buttonStatisticsPage")
        self.verticalLayout_2.addWidget(self.buttonStatisticsPage)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.leftMenuFrame)
        self.containerStackedWidget = QtWidgets.QStackedWidget(self.mainWidget)
        self.containerStackedWidget.setMinimumSize(QtCore.QSize(390, 0))
        self.containerStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.containerStackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerStackedWidget.setObjectName("containerStackedWidget")
        self.ProductPage = QtWidgets.QWidget()
        self.ProductPage.setObjectName("ProductPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ProductPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.ProductPage)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelProductTableCount = QtWidgets.QLabel(self.frame)
        self.labelProductTableCount.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelProductTableCount.setFont(font)
        self.labelProductTableCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelProductTableCount.setObjectName("labelProductTableCount")
        self.gridLayout.addWidget(self.labelProductTableCount, 4, 3, 1, 1)
        self.searchFrame = QtWidgets.QFrame(self.frame)
        self.searchFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.searchFrame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_4.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchButtonIcon = QtWidgets.QPushButton(self.searchFrame)
        self.searchButtonIcon.setMinimumSize(QtCore.QSize(0, 0))
        self.searchButtonIcon.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cil-magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButtonIcon.setIcon(icon3)
        self.searchButtonIcon.setIconSize(QtCore.QSize(25, 25))
        self.searchButtonIcon.setObjectName("searchButtonIcon")
        self.horizontalLayout_4.addWidget(self.searchButtonIcon)
        self.lineEditSearchProduct = QtWidgets.QLineEdit(self.searchFrame)
        self.lineEditSearchProduct.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEditSearchProduct.setFont(font)
        self.lineEditSearchProduct.setObjectName("lineEditSearchProduct")
        self.horizontalLayout_4.addWidget(self.lineEditSearchProduct)
        self.gridLayout.addWidget(self.searchFrame, 4, 0, 1, 1)
        self.comboBoxProductBy = QtWidgets.QComboBox(self.frame)
        self.comboBoxProductBy.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxProductBy.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.comboBoxProductBy.setFont(font)
        self.comboBoxProductBy.setObjectName("comboBoxProductBy")
        self.comboBoxProductBy.addItem("")
        self.comboBoxProductBy.addItem("")
        self.comboBoxProductBy.addItem("")
        self.comboBoxProductBy.addItem("")
        self.gridLayout.addWidget(self.comboBoxProductBy, 2, 0, 1, 1)
        self.labelErrorProductPage = QtWidgets.QLabel(self.frame)
        self.labelErrorProductPage.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelErrorProductPage.setFont(font)
        self.labelErrorProductPage.setObjectName("labelErrorProductPage")
        self.gridLayout.addWidget(self.labelErrorProductPage, 2, 3, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.frameToolButton_3 = QtWidgets.QFrame(self.ProductPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton_3.sizePolicy().hasHeightForWidth())
        self.frameToolButton_3.setSizePolicy(sizePolicy)
        self.frameToolButton_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton_3.setObjectName("frameToolButton_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frameToolButton_3)
        self.horizontalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.buttonProductDetails = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonProductDetails.sizePolicy().hasHeightForWidth())
        self.buttonProductDetails.setSizePolicy(sizePolicy)
        self.buttonProductDetails.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonProductDetails.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonProductDetails.setText("")
        self.buttonProductDetails.setIconSize(QtCore.QSize(27, 27))
        self.buttonProductDetails.setObjectName("buttonProductDetails")
        self.horizontalLayout_12.addWidget(self.buttonProductDetails)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.buttonNewProduct = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNewProduct.sizePolicy().hasHeightForWidth())
        self.buttonNewProduct.setSizePolicy(sizePolicy)
        self.buttonNewProduct.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonNewProduct.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonNewProduct.setText("")
        self.buttonNewProduct.setIconSize(QtCore.QSize(27, 27))
        self.buttonNewProduct.setObjectName("buttonNewProduct")
        self.horizontalLayout_12.addWidget(self.buttonNewProduct)
        self.buttonEditProduct = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEditProduct.sizePolicy().hasHeightForWidth())
        self.buttonEditProduct.setSizePolicy(sizePolicy)
        self.buttonEditProduct.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonEditProduct.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonEditProduct.setText("")
        self.buttonEditProduct.setIconSize(QtCore.QSize(27, 27))
        self.buttonEditProduct.setObjectName("buttonEditProduct")
        self.horizontalLayout_12.addWidget(self.buttonEditProduct)
        self.buttonDeleteProduct = QtWidgets.QPushButton(self.frameToolButton_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteProduct.sizePolicy().hasHeightForWidth())
        self.buttonDeleteProduct.setSizePolicy(sizePolicy)
        self.buttonDeleteProduct.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDeleteProduct.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDeleteProduct.setText("")
        self.buttonDeleteProduct.setIconSize(QtCore.QSize(27, 27))
        self.buttonDeleteProduct.setObjectName("buttonDeleteProduct")
        self.horizontalLayout_12.addWidget(self.buttonDeleteProduct)
        self.verticalLayout_4.addWidget(self.frameToolButton_3)
        self.tableWidgetProduct = QtWidgets.QTableWidget(self.ProductPage)
        self.tableWidgetProduct.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetProduct.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetProduct.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetProduct.setObjectName("tableWidgetProduct")
        self.tableWidgetProduct.setColumnCount(3)
        self.tableWidgetProduct.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProduct.setItem(1, 2, item)
        self.tableWidgetProduct.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidgetProduct.horizontalHeader().setHighlightSections(False)
        self.tableWidgetProduct.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetProduct.verticalHeader().setVisible(False)
        self.tableWidgetProduct.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.tableWidgetProduct)
        self.containerStackedWidget.addWidget(self.ProductPage)
        self.OrderPage = QtWidgets.QWidget()
        self.OrderPage.setObjectName("OrderPage")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.OrderPage)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_2 = QtWidgets.QFrame(self.OrderPage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBoxOrderBy = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxOrderBy.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBoxOrderBy.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.comboBoxOrderBy.setFont(font)
        self.comboBoxOrderBy.setObjectName("comboBoxOrderBy")
        self.comboBoxOrderBy.addItem("")
        self.comboBoxOrderBy.addItem("")
        self.comboBoxOrderBy.addItem("")
        self.comboBoxOrderBy.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxOrderBy, 2, 0, 1, 1)
        self.labelErrorOrderPage = QtWidgets.QLabel(self.frame_2)
        self.labelErrorOrderPage.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelErrorOrderPage.setFont(font)
        self.labelErrorOrderPage.setObjectName("labelErrorOrderPage")
        self.gridLayout_3.addWidget(self.labelErrorOrderPage, 2, 3, 1, 1)
        self.verticalLayout_15.addWidget(self.frame_2)
        self.frameToolButton = QtWidgets.QFrame(self.OrderPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton.sizePolicy().hasHeightForWidth())
        self.frameToolButton.setSizePolicy(sizePolicy)
        self.frameToolButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton.setObjectName("frameToolButton")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frameToolButton)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.searchFrame_2 = QtWidgets.QFrame(self.frameToolButton)
        self.searchFrame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.searchFrame_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.searchFrame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame_2.setObjectName("searchFrame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.searchFrame_2)
        self.horizontalLayout_10.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout_10.setSpacing(2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.searchButtonIcon_2 = QtWidgets.QPushButton(self.searchFrame_2)
        self.searchButtonIcon_2.setMinimumSize(QtCore.QSize(0, 0))
        self.searchButtonIcon_2.setText("")
        self.searchButtonIcon_2.setIcon(icon3)
        self.searchButtonIcon_2.setIconSize(QtCore.QSize(25, 25))
        self.searchButtonIcon_2.setObjectName("searchButtonIcon_2")
        self.horizontalLayout_10.addWidget(self.searchButtonIcon_2)
        self.lineEditSearchOrder = QtWidgets.QLineEdit(self.searchFrame_2)
        self.lineEditSearchOrder.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEditSearchOrder.setFont(font)
        self.lineEditSearchOrder.setObjectName("lineEditSearchOrder")
        self.horizontalLayout_10.addWidget(self.lineEditSearchOrder)
        self.horizontalLayout_5.addWidget(self.searchFrame_2)
        self.labelOrderTableCount = QtWidgets.QLabel(self.frameToolButton)
        self.labelOrderTableCount.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelOrderTableCount.setFont(font)
        self.labelOrderTableCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOrderTableCount.setObjectName("labelOrderTableCount")
        self.horizontalLayout_5.addWidget(self.labelOrderTableCount)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.buttonOrderDetails = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOrderDetails.sizePolicy().hasHeightForWidth())
        self.buttonOrderDetails.setSizePolicy(sizePolicy)
        self.buttonOrderDetails.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonOrderDetails.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonOrderDetails.setText("")
        self.buttonOrderDetails.setIconSize(QtCore.QSize(27, 27))
        self.buttonOrderDetails.setObjectName("buttonOrderDetails")
        self.horizontalLayout_5.addWidget(self.buttonOrderDetails)
        self.buttonNewOrder = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNewOrder.sizePolicy().hasHeightForWidth())
        self.buttonNewOrder.setSizePolicy(sizePolicy)
        self.buttonNewOrder.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonNewOrder.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonNewOrder.setText("")
        self.buttonNewOrder.setIconSize(QtCore.QSize(27, 27))
        self.buttonNewOrder.setObjectName("buttonNewOrder")
        self.horizontalLayout_5.addWidget(self.buttonNewOrder)
        self.buttonEditOrder = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEditOrder.sizePolicy().hasHeightForWidth())
        self.buttonEditOrder.setSizePolicy(sizePolicy)
        self.buttonEditOrder.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonEditOrder.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonEditOrder.setText("")
        self.buttonEditOrder.setIconSize(QtCore.QSize(27, 27))
        self.buttonEditOrder.setObjectName("buttonEditOrder")
        self.horizontalLayout_5.addWidget(self.buttonEditOrder)
        self.buttonDeleteOrder = QtWidgets.QPushButton(self.frameToolButton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDeleteOrder.sizePolicy().hasHeightForWidth())
        self.buttonDeleteOrder.setSizePolicy(sizePolicy)
        self.buttonDeleteOrder.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDeleteOrder.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDeleteOrder.setText("")
        self.buttonDeleteOrder.setIconSize(QtCore.QSize(27, 27))
        self.buttonDeleteOrder.setObjectName("buttonDeleteOrder")
        self.horizontalLayout_5.addWidget(self.buttonDeleteOrder)
        self.verticalLayout_15.addWidget(self.frameToolButton)
        self.tableWidgetOrders = QtWidgets.QTableWidget(self.OrderPage)
        self.tableWidgetOrders.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidgetOrders.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetOrders.setObjectName("tableWidgetOrders")
        self.tableWidgetOrders.setColumnCount(3)
        self.tableWidgetOrders.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOrders.setItem(1, 2, item)
        self.tableWidgetOrders.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidgetOrders.horizontalHeader().setHighlightSections(False)
        self.tableWidgetOrders.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetOrders.verticalHeader().setVisible(False)
        self.tableWidgetOrders.verticalHeader().setHighlightSections(False)
        self.verticalLayout_15.addWidget(self.tableWidgetOrders)
        self.containerStackedWidget.addWidget(self.OrderPage)
        self.statisticsPage = QtWidgets.QWidget()
        self.statisticsPage.setObjectName("statisticsPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.statisticsPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 116, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.stackedWidgetInfoCard = QtWidgets.QStackedWidget(self.statisticsPage)
        self.stackedWidgetInfoCard.setMinimumSize(QtCore.QSize(0, 350))
        self.stackedWidgetInfoCard.setStyleSheet("")
        self.stackedWidgetInfoCard.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidgetInfoCard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stackedWidgetInfoCard.setObjectName("stackedWidgetInfoCard")
        self.stWidgetInfoPage = QtWidgets.QWidget()
        self.stWidgetInfoPage.setObjectName("stWidgetInfoPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.stWidgetInfoPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridFrame = QtWidgets.QFrame(self.stWidgetInfoPage)
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.gridFrame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/cil-clipboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 1, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gridFrame)
        self.tableWidgetProcessConnections = QtWidgets.QTableWidget(self.stWidgetInfoPage)
        self.tableWidgetProcessConnections.setObjectName("tableWidgetProcessConnections")
        self.tableWidgetProcessConnections.setColumnCount(0)
        self.tableWidgetProcessConnections.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidgetProcessConnections)
        self.stackedWidgetInfoCard.addWidget(self.stWidgetInfoPage)
        self.stWidgetOsInfoPage = QtWidgets.QWidget()
        self.stWidgetOsInfoPage.setMaximumSize(QtCore.QSize(800, 16777215))
        self.stWidgetOsInfoPage.setObjectName("stWidgetOsInfoPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.stWidgetOsInfoPage)
        self.verticalLayout_14.setSpacing(15)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelName = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelName.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelName.setObjectName("labelName")
        self.verticalLayout_8.addWidget(self.labelName)
        self.labelNameValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelNameValue.setObjectName("labelNameValue")
        self.verticalLayout_8.addWidget(self.labelNameValue)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.labelVersion = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelVersion.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelVersion.setObjectName("labelVersion")
        self.verticalLayout_9.addWidget(self.labelVersion)
        self.labelVersionValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelVersionValue.setObjectName("labelVersionValue")
        self.verticalLayout_9.addWidget(self.labelVersionValue)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.labelPlatform = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelPlatform.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelPlatform.setObjectName("labelPlatform")
        self.verticalLayout_10.addWidget(self.labelPlatform)
        self.labelPlatformValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelPlatformValue.setObjectName("labelPlatformValue")
        self.verticalLayout_10.addWidget(self.labelPlatformValue)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.labelArch = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelArch.setFont(font)
        self.labelArch.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelArch.setObjectName("labelArch")
        self.verticalLayout_11.addWidget(self.labelArch)
        self.labelArchValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelArchValue.setObjectName("labelArchValue")
        self.verticalLayout_11.addWidget(self.labelArchValue)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.labelCpu = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelCpu.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelCpu.setObjectName("labelCpu")
        self.verticalLayout_12.addWidget(self.labelCpu)
        self.labelCpuValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelCpuValue.setObjectName("labelCpuValue")
        self.verticalLayout_12.addWidget(self.labelCpuValue)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelRam = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelRam.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.labelRam.setObjectName("labelRam")
        self.verticalLayout_13.addWidget(self.labelRam)
        self.labelRamValue = QtWidgets.QLabel(self.stWidgetOsInfoPage)
        self.labelRamValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelRamValue.setObjectName("labelRamValue")
        self.verticalLayout_13.addWidget(self.labelRamValue)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem7)
        self.stackedWidgetInfoCard.addWidget(self.stWidgetOsInfoPage)
        self.verticalLayout_6.addWidget(self.stackedWidgetInfoCard)
        spacerItem8 = QtWidgets.QSpacerItem(20, 116, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.containerStackedWidget.addWidget(self.statisticsPage)
        self.horizontalLayout.addWidget(self.containerStackedWidget)
        self.horizontalLayout_9.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.NoDockWidgetFeatures)
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rightFrame = QtWidgets.QFrame(self.dockWidgetContents)
        self.rightFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.rightFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.rightFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightFrame.setObjectName("rightFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleFrame = QtWidgets.QFrame(self.rightFrame)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCloseCard = QtWidgets.QPushButton(self.titleFrame)
        self.buttonCloseCard.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonCloseCard.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonCloseCard.setText("")
        self.buttonCloseCard.setIconSize(QtCore.QSize(25, 25))
        self.buttonCloseCard.setObjectName("buttonCloseCard")
        self.horizontalLayout_2.addWidget(self.buttonCloseCard)
        self.labelTitle = QtWidgets.QLabel(self.titleFrame)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setWordWrap(True)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_2.addWidget(self.labelTitle)
        self.verticalLayout_3.addWidget(self.titleFrame)
        self.frameToolButton_2 = QtWidgets.QFrame(self.rightFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolButton_2.sizePolicy().hasHeightForWidth())
        self.frameToolButton_2.setSizePolicy(sizePolicy)
        self.frameToolButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frameToolButton_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameToolButton_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolButton_2.setObjectName("frameToolButton_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frameToolButton_2)
        self.horizontalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.buttonDetailsMoreInfo_2 = QtWidgets.QPushButton(self.frameToolButton_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDetailsMoreInfo_2.sizePolicy().hasHeightForWidth())
        self.buttonDetailsMoreInfo_2.setSizePolicy(sizePolicy)
        self.buttonDetailsMoreInfo_2.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDetailsMoreInfo_2.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDetailsMoreInfo_2.setText("")
        self.buttonDetailsMoreInfo_2.setIconSize(QtCore.QSize(27, 27))
        self.buttonDetailsMoreInfo_2.setObjectName("buttonDetailsMoreInfo_2")
        self.horizontalLayout_11.addWidget(self.buttonDetailsMoreInfo_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.buttonSave = QtWidgets.QPushButton(self.frameToolButton_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSave.sizePolicy().hasHeightForWidth())
        self.buttonSave.setSizePolicy(sizePolicy)
        self.buttonSave.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonSave.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonSave.setText("")
        self.buttonSave.setIconSize(QtCore.QSize(27, 27))
        self.buttonSave.setObjectName("buttonSave")
        self.horizontalLayout_11.addWidget(self.buttonSave)
        self.buttonDetailsEdit_2 = QtWidgets.QPushButton(self.frameToolButton_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDetailsEdit_2.sizePolicy().hasHeightForWidth())
        self.buttonDetailsEdit_2.setSizePolicy(sizePolicy)
        self.buttonDetailsEdit_2.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDetailsEdit_2.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDetailsEdit_2.setText("")
        self.buttonDetailsEdit_2.setIconSize(QtCore.QSize(27, 27))
        self.buttonDetailsEdit_2.setObjectName("buttonDetailsEdit_2")
        self.horizontalLayout_11.addWidget(self.buttonDetailsEdit_2)
        self.buttonDetailsDelete_2 = QtWidgets.QPushButton(self.frameToolButton_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDetailsDelete_2.sizePolicy().hasHeightForWidth())
        self.buttonDetailsDelete_2.setSizePolicy(sizePolicy)
        self.buttonDetailsDelete_2.setMinimumSize(QtCore.QSize(40, 40))
        self.buttonDetailsDelete_2.setMaximumSize(QtCore.QSize(40, 40))
        self.buttonDetailsDelete_2.setText("")
        self.buttonDetailsDelete_2.setIconSize(QtCore.QSize(27, 27))
        self.buttonDetailsDelete_2.setObjectName("buttonDetailsDelete_2")
        self.horizontalLayout_11.addWidget(self.buttonDetailsDelete_2)
        self.verticalLayout_3.addWidget(self.frameToolButton_2)
        self.scrollArea = QtWidgets.QScrollArea(self.rightFrame)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 300, 454))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frameDetailsID = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameDetailsID.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameDetailsID.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDetailsID.setObjectName("frameDetailsID")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frameDetailsID)
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelOperation = QtWidgets.QLabel(self.frameDetailsID)
        self.labelOperation.setObjectName("labelOperation")
        self.horizontalLayout_8.addWidget(self.labelOperation)
        self.labelItemID = QtWidgets.QLabel(self.frameDetailsID)
        self.labelItemID.setText("")
        self.labelItemID.setObjectName("labelItemID")
        self.horizontalLayout_8.addWidget(self.labelItemID)
        self.labelMongoTable = QtWidgets.QLabel(self.frameDetailsID)
        self.labelMongoTable.setText("")
        self.labelMongoTable.setObjectName("labelMongoTable")
        self.horizontalLayout_8.addWidget(self.labelMongoTable)
        self.verticalLayout_5.addWidget(self.frameDetailsID)
        self.formFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formFrame.sizePolicy().hasHeightForWidth())
        self.formFrame.setSizePolicy(sizePolicy)
        self.formFrame.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_5.addWidget(self.formFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.rightFrame)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)

        self.retranslateUi(MainWindow)
        self.containerStackedWidget.setCurrentIndex(1)
        self.stackedWidgetInfoCard.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonUsername.setText(_translate("MainWindow", "الإسم"))
        self.buttonProductPage.setText(_translate("MainWindow", "السلعة"))
        self.buttonOrderPage.setText(_translate("MainWindow", "الطلبيات"))
        self.buttonStatisticsPage.setText(_translate("MainWindow", "الإحصائيات"))
        self.labelProductTableCount.setText(_translate("MainWindow", "المجموع"))
        self.lineEditSearchProduct.setToolTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchProduct.setStatusTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchProduct.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.comboBoxProductBy.setStatusTip(_translate("MainWindow", "Process By Owner"))
        self.comboBoxProductBy.setPlaceholderText(_translate("MainWindow", "Process By Username"))
        self.comboBoxProductBy.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBoxProductBy.setItemText(3, _translate("MainWindow", "New Item"))
        self.labelErrorProductPage.setText(_translate("MainWindow", "Error Label"))
        self.buttonNewProduct.setToolTip(_translate("MainWindow", "Terminate "))
        self.buttonNewProduct.setStatusTip(_translate("MainWindow", "Terminate "))
        self.buttonEditProduct.setToolTip(_translate("MainWindow", "Edit"))
        self.buttonEditProduct.setStatusTip(_translate("MainWindow", "Edit"))
        self.buttonDeleteProduct.setToolTip(_translate("MainWindow", "Delete"))
        self.buttonDeleteProduct.setStatusTip(_translate("MainWindow", "Delete"))
        self.tableWidgetProduct.setSortingEnabled(True)
        item = self.tableWidgetProduct.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PID"))
        item = self.tableWidgetProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAM"))
        item = self.tableWidgetProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        __sortingEnabled = self.tableWidgetProduct.isSortingEnabled()
        self.tableWidgetProduct.setSortingEnabled(False)
        item = self.tableWidgetProduct.item(0, 0)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetProduct.item(0, 1)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetProduct.item(0, 2)
        item.setText(_translate("MainWindow", "runing"))
        item = self.tableWidgetProduct.item(1, 0)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetProduct.item(1, 1)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetProduct.item(1, 2)
        item.setText(_translate("MainWindow", "runing"))
        self.tableWidgetProduct.setSortingEnabled(__sortingEnabled)
        self.comboBoxOrderBy.setStatusTip(_translate("MainWindow", "Process By Owner"))
        self.comboBoxOrderBy.setPlaceholderText(_translate("MainWindow", "Process By Username"))
        self.comboBoxOrderBy.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBoxOrderBy.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBoxOrderBy.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBoxOrderBy.setItemText(3, _translate("MainWindow", "New Item"))
        self.labelErrorOrderPage.setText(_translate("MainWindow", "Error Label"))
        self.lineEditSearchOrder.setToolTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchOrder.setStatusTip(_translate("MainWindow", "بحث عن سلعة بالإسم"))
        self.lineEditSearchOrder.setPlaceholderText(_translate("MainWindow", "بحث"))
        self.labelOrderTableCount.setText(_translate("MainWindow", "المجموع"))
        self.buttonNewOrder.setToolTip(_translate("MainWindow", "Terminate "))
        self.buttonNewOrder.setStatusTip(_translate("MainWindow", "Terminate "))
        self.buttonEditOrder.setToolTip(_translate("MainWindow", "Edit"))
        self.buttonEditOrder.setStatusTip(_translate("MainWindow", "Edit"))
        self.buttonDeleteOrder.setToolTip(_translate("MainWindow", "Delete"))
        self.buttonDeleteOrder.setStatusTip(_translate("MainWindow", "Delete"))
        self.tableWidgetOrders.setSortingEnabled(True)
        item = self.tableWidgetOrders.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidgetOrders.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PID"))
        item = self.tableWidgetOrders.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NAM"))
        item = self.tableWidgetOrders.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STATUS"))
        __sortingEnabled = self.tableWidgetOrders.isSortingEnabled()
        self.tableWidgetOrders.setSortingEnabled(False)
        item = self.tableWidgetOrders.item(0, 0)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetOrders.item(0, 1)
        item.setText(_translate("MainWindow", "python"))
        item = self.tableWidgetOrders.item(0, 2)
        item.setText(_translate("MainWindow", "runing"))
        item = self.tableWidgetOrders.item(1, 0)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetOrders.item(1, 1)
        item.setText(_translate("MainWindow", "firefox"))
        item = self.tableWidgetOrders.item(1, 2)
        item.setText(_translate("MainWindow", "runing"))
        self.tableWidgetOrders.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Copy "))
        self.labelName.setText(_translate("MainWindow", "Name"))
        self.labelNameValue.setText(_translate("MainWindow", "Value"))
        self.labelVersion.setText(_translate("MainWindow", "Version"))
        self.labelVersionValue.setText(_translate("MainWindow", "Value"))
        self.labelPlatform.setText(_translate("MainWindow", "Platform"))
        self.labelPlatformValue.setText(_translate("MainWindow", "Value"))
        self.labelArch.setText(_translate("MainWindow", "Architecture"))
        self.labelArchValue.setText(_translate("MainWindow", "Value"))
        self.labelCpu.setText(_translate("MainWindow", "Cpu"))
        self.labelCpuValue.setText(_translate("MainWindow", "Value"))
        self.labelRam.setText(_translate("MainWindow", "Ram"))
        self.labelRamValue.setText(_translate("MainWindow", "Value"))
        self.labelTitle.setText(_translate("MainWindow", "معلومات إضافية"))
        self.buttonSave.setToolTip(_translate("MainWindow", "Terminate "))
        self.buttonSave.setStatusTip(_translate("MainWindow", "Terminate "))
        self.buttonDetailsEdit_2.setToolTip(_translate("MainWindow", "Edit"))
        self.buttonDetailsEdit_2.setStatusTip(_translate("MainWindow", "Edit"))
        self.buttonDetailsDelete_2.setToolTip(_translate("MainWindow", "Delete"))
        self.buttonDetailsDelete_2.setStatusTip(_translate("MainWindow", "Delete"))
        self.labelOperation.setText(_translate("MainWindow", "TextLabel"))
import resource_rc
