# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ui_addProductToCart.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddToCart(object):
    def setupUi(self, AddToCart):
        AddToCart.setObjectName("AddToCart")
        AddToCart.resize(417, 293)
        AddToCart.setStyleSheet("#centralWidget {\n"
"    background-color: #2f2f2f;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"#labelTitle {    \n"
"    font: 18pt \"Noto Traditional Nushu\";\n"
"    border: 2px solid #444444;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"QSpinBox {\n"
"    font: 12pt \"Noto Serif Thai\";\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    background: #393836;\n"
"    border: none;\n"
"    padding: 5px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border: 2px solid #4c4c4c;\n"
"}\n"
"\n"
"QSpinBox:focus\n"
"{\n"
"    background-color: rgba(51, 50, 50, 172);\n"
"    border: 2px solid #4c4c4c;\n"
"}\n"
"\n"
"/********************\n"
"    QPushButton\n"
"************************/\n"
"QPushButton {\n"
"    border-radius: 17px;\n"
"    padding: 3px 0;\n"
"    background-color: #2f2f2f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #575757;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424242;\n"
"}\n"
"\n"
"#buttonConfirm {\n"
"    background-color: #1abc9c;\n"
"}\n"
"\n"
"#buttonConfirm:hover {\n"
"    background-color: #16a085;\n"
"}\n"
"\n"
"/********************\n"
"    QComboBox\n"
"***********************/\n"
"QComboBox {\n"
"    font: 12pt \"Droid Sans Fallback\";\n"
"    background-color: #32312f;\n"
"    color: #ffffff;\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgb(64, 66, 72);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    combobox-popup: 0;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid #4c4c4c;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px;\n"
"    border-right-width: 3px;\n"
"    border-right-color: #4c4c4c;\n"
"    border-right-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-image: url(:/icons/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #4b7bec; /*rgb(255, 121, 198);    */\n"
"    background-color: transparent;\n"
"    padding: 10px 7px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"    border: 2px solid #4c4c4c;\n"
"    border-top: none;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 12px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddToCart)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralWidget = QtWidgets.QWidget(AddToCart)
        self.centralWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTitle = QtWidgets.QLabel(self.centralWidget)
        self.labelTitle.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Noto Traditional Nushu")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_2.addWidget(self.labelTitle)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setHorizontalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Noto Traditional Nushu")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Noto Traditional Nushu")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBoxQte = QtWidgets.QSpinBox(self.frame_2)
        self.spinBoxQte.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxQte.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxQte.setMaximum(100000)
        self.spinBoxQte.setObjectName("spinBoxQte")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxQte)
        self.comboBoxProduct = QtWidgets.QComboBox(self.frame_2)
        self.comboBoxProduct.setObjectName("comboBoxProduct")
        self.comboBoxProduct.addItem("")
        self.comboBoxProduct.addItem("")
        self.comboBoxProduct.addItem("")
        self.comboBoxProduct.addItem("")
        self.comboBoxProduct.addItem("")
        self.comboBoxProduct.addItem("")
        self.comboBoxProduct.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxProduct)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonCancel = QtWidgets.QPushButton(self.frame)
        self.buttonCancel.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.buttonConfirm = QtWidgets.QPushButton(self.frame)
        self.buttonConfirm.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        self.buttonConfirm.setFont(font)
        self.buttonConfirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonConfirm.setObjectName("buttonConfirm")
        self.horizontalLayout.addWidget(self.buttonConfirm)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.centralWidget)

        self.retranslateUi(AddToCart)
        QtCore.QMetaObject.connectSlotsByName(AddToCart)

    def retranslateUi(self, AddToCart):
        _translate = QtCore.QCoreApplication.translate
        AddToCart.setWindowTitle(_translate("AddToCart", "Dialog"))
        self.labelTitle.setText(_translate("AddToCart", "إضافة منتج"))
        self.label.setText(_translate("AddToCart", "إختر منتجا"))
        self.label_2.setText(_translate("AddToCart", "الكمية"))
        self.comboBoxProduct.setItemText(0, _translate("AddToCart", "New Item"))
        self.comboBoxProduct.setItemText(1, _translate("AddToCart", "New Item"))
        self.comboBoxProduct.setItemText(2, _translate("AddToCart", "New Item"))
        self.comboBoxProduct.setItemText(3, _translate("AddToCart", "New Item"))
        self.comboBoxProduct.setItemText(4, _translate("AddToCart", "New Item"))
        self.comboBoxProduct.setItemText(5, _translate("AddToCart", "New Item"))
        self.comboBoxProduct.setItemText(6, _translate("AddToCart", "New Item"))
        self.buttonCancel.setText(_translate("AddToCart", "إلغاء"))
        self.buttonConfirm.setText(_translate("AddToCart", "إضافة"))
import resource_rc
