# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ui_confirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 265)
        Dialog.setStyleSheet("QDialog {\n"
"    background: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#centralWidget {\n"
"    background-color: #2f2f2f;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #ffffff;\n"
"    padding: 25px 10px;\n"
"}\n"
"\n"
"#labelTitle {\n"
"    border: 2px solid #444444;\n"
"    border-top: none;\n"
"    border-left: none;\n"
"    border-right: none;\n"
"}\n"
"QPushButton {\n"
"    border-radius: 17px;\n"
"    padding: 3px 0;\n"
"    background-color: #2f2f2f;\n"
"    color: #ffffff;\n"
"    border: 1px solid #575757;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #424242;\n"
"}\n"
"\n"
"#buttonConfirm {\n"
"    background-color: #ef4444;\n"
"}\n"
"\n"
"#buttonConfirm:hover {\n"
"    background-color: #b91c1c;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.centralWidget = QtWidgets.QWidget(Dialog)
        self.centralWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralWidget.setStyleSheet("")
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTitle = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelTitle.setFont(font)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_2.addWidget(self.labelTitle)
        self.labelMessage = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelMessage.setFont(font)
        self.labelMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_2.addWidget(self.labelMessage)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(253, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.buttonCancel = QtWidgets.QPushButton(self.frame)
        self.buttonCancel.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        self.buttonCancel.setFont(font)
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonCancel.setObjectName("buttonCancel")
        self.horizontalLayout.addWidget(self.buttonCancel)
        self.buttonConfirm = QtWidgets.QPushButton(self.frame)
        self.buttonConfirm.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Fallback")
        font.setPointSize(12)
        self.buttonConfirm.setFont(font)
        self.buttonConfirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonConfirm.setObjectName("buttonConfirm")
        self.horizontalLayout.addWidget(self.buttonConfirm)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.centralWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelTitle.setText(_translate("Dialog", "حذف المنتج"))
        self.labelMessage.setText(_translate("Dialog", "Are you sure to delete item"))
        self.buttonCancel.setText(_translate("Dialog", "لا"))
        self.buttonConfirm.setText(_translate("Dialog", "حذف"))
